# Copyright 2022 Canonical Ltd.
# See LICENSE file for licensing details.

options:
  vendor_telemetry:
    description: |
      Toggles whether to send telemetry to the vendor, i.e. Grafana.
      If your deployment is airgapped, turn this off.
    type: boolean
    default: true
  tls_insecure_skip_verify:
    description: |
      Flag to skip the verification for insecure TLS.
      If "true", self-signed certs can be seamlessly used; this setting
      will be applied to all of the Agent configurations (Prometheus,
      Loki).
    type: boolean
    default: false
  global_scrape_timeout:
    description: >
      How long to wait before timing out a scrape from a target.
      Supported units: y, w, d, h, m, s.
    type: string
    default: "10s"
  global_scrape_interval:
    description: >
      How frequently should instances be scraped.
      Supported units: y, w, d, h, m, s.
    type: string
    default: "1m"
